### ISSUE TITLE
failing to contect to dexcom g6

### ISSUE THREAD

**Issue by GENERICERROR000** [xdrip-js/xdrip-js#124]
hi - if anyone is still checking issues...

i'm currently running this project on a `Raspberry Pi 4 Model B`. i was able to get it to work with the latest version of nodejs by replacing noble with another, maintained version `@abandonware/noble`. however, i am now encountering another issue, and my understanding of the bluetooth is limited to say the least.

there are two sets of outputs below. they differ by `alternateBluetoothChannel` being true or false. when true, the set timeout to run again doesn't run, the script just stops.

any help would be appreciated. would be happy to take a stab at fixing if someone is able to provide more context. the error is created here in the code: `lib/bluetooth-manager.js: line 153`. thank you!

please see details below:

## running with `alternateBluetoothChannel: false`

*run command*

```bash
sudo DEBUG=smp,transmitter,bluetooth-manager node example <transmitter-id>
```

*error*

```
Error: Unable to parse auth challenge: received 0193454344ba1f424d02, expecting 3
```

*output*

```
transmitter Listening for transmitter <transmitter-id> +0ms
bluetooth-manager on -> stateChange: poweredOn +0ms
bluetooth-manager starting scanning +1ms
bluetooth-manager on -> scanStart +3ms
bluetooth-manager Sat Jul 15 2023 15:34:18 GMT-0400 (Eastern Daylight Time): peripheral: DexcomUR with rssi -86 +15s
bluetooth-manager Sat Jul 15 2023 15:35:33 GMT-0400 (Eastern Daylight Time): peripheral: DexcomD4 with rssi -90 +1m
bluetooth-manager Sat Jul 15 2023 15:36:35 GMT-0400 (Eastern Daylight Time): peripheral: DexcomMJ with rssi -65 +1m
bluetooth-manager on -> scanStop +2s
bluetooth-manager on -> scanStart +1ms
bluetooth-manager on -> connect +9ms
bluetooth-manager on -> peripheral services discovered +170ms
bluetooth-manager on -> service characteristics discovered +338ms
transmitter Authenticating with transmitter, alternate bt channel: false +3m
bluetooth-manager Tx 0193454344ba1f424d02 +43ms
bluetooth-manager Rx 0193454344ba1f424d02 +68ms
transmitter Error: Unable to parse auth challenge: received 0193454344ba1f424d02, expecting 3
transmitter     at Transmitter.authenticate (/home/cgmine/code/cgm/xdrip-js/lib/transmitter.js:86:11)
transmitter     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
transmitter     at async Transmitter.isReady (/home/cgmine/code/cgm/xdrip-js/lib/transmitter.js:436:22) +110ms
transmitter Initiating a disconnect +2ms
bluetooth-manager setting notify to false +5ms
bluetooth-manager disconnected peripheral +132ms
bluetooth-manager scanning again in 1 minute +2ms
```

## running with `alternateBluetoothChannel: true`

*run command*

```bash
sudo DEBUG=smp,transmitter,bluetooth-manager node example <transmitter-id>
```

*output*

```
transmitter Listening for transmitter <transmitter-id> +0ms
bluetooth-manager on -> stateChange: poweredOn +0ms
bluetooth-manager starting scanning +0ms
bluetooth-manager on -> scanStart +3ms
bluetooth-manager Sat Jul 15 2023 16:59:18 GMT-0400 (Eastern Daylight Time): peripheral: DexcomUR with rssi -86 +3m
bluetooth-manager Sat Jul 15 2023 17:00:33 GMT-0400 (Eastern Daylight Time): peripheral: DexcomD4 with rssi -92 +1m
bluetooth-manager Sat Jul 15 2023 17:01:35 GMT-0400 (Eastern Daylight Time): peripheral: DexcomMJ with rssi -72 +1m
bluetooth-manager on -> scanStop +252ms
bluetooth-manager on -> scanStart +3ms
bluetooth-manager on -> connect +12ms
bluetooth-manager on -> peripheral services discovered +189ms
bluetooth-manager on -> service characteristics discovered +337ms
transmitter Authenticating with transmitter, alternate bt channel: true +5m
bluetooth-manager Tx 010c3deb309bae473501 +66ms
bluetooth-manager Rx 03326859f3ae76cef1a9d98f2efc04ef29 +46ms
bluetooth-manager Tx 04fe90cba95acf733a +66ms
bluetooth-manager Rx 050102 +45ms
transmitter transmitter responded with status message 050102 +222ms
transmitter Requesting bond +0ms
bluetooth-manager Tx 0619 +45ms
bluetooth-manager Tx 07 +45ms
transmitter Bonding request sent. Waiting for user to respond. +90ms
bluetooth-manager setting notify to true +3ms
bluetooth-manager disconnected peripheral +160ms
bluetooth-manager scanning again in 1 minute +0ms
```

**Comment by jpcunningh** [comment]
Are you using a phone app? The "alternateBluetoothChannel" option just sets a value in the message to the transmitter to tell the transmitter whether the connecting device is a phone or a receiver. The transmitter only supports two devices at one time, one phone and one receiver.

alternateBluetoothChannel allows you to configure xdrip-js to tell the transmitter whether it is a phone or a transmitter. It looks normal for the second output if you have another device paired to the transmitter and receiving readings from it. You have to disable connectivity for >15 minutes from the existing phone or receiver before the transmitter will accept a pairing from a different device of the same type.

The real problem I think that needs to be resolved is in the first output log where it received a message that it didn't recognize: 0193454344ba1f424d02. The message appears to have been a copy of the message that was sent?

I'm looking for a raspberry pi zero 2 w. As soon as I can get my hands on one, I'm going to try to get it up and running. I didn't have much success with the raspberry pi zero w boards. They would work fine for a while, then stop being able to successfully complete a full round of communication with the transmitter for a period of time, sometimes hours. After a while, it would just start working again.

**Comment by GENERICERROR000** [comment]
thank you so much @jpcunningh for the response! see my comments below.

> Are you using a phone app? The "alternateBluetoothChannel" option just sets a value in the message to the transmitter to tell the transmitter whether the connecting device is a phone or a receiver. The transmitter only supports two devices at one time, one phone and one receiver.

1. i'm currently using the dexacom mobile app on an iphone. so, based on this, i should be setting "alternateBluetoothChannel" to true, as the phone slot/port is being used.

> alternateBluetoothChannel allows you to configure xdrip-js to tell the transmitter whether it is a phone or a transmitter. It looks normal for the second output if you have another device paired to the transmitter and receiving readings from it. You have to disable connectivity for >15 minutes from the existing phone or receiver before the transmitter will accept a pairing from a different device of the same type.

2. if i understand correctly, i should be able to connect a phone and a reciever (in this case my rpi) at the same time to one transmitter. this makes sense - although complicates the outputs i am seeing. 

when "alternateBluetoothChannel" is false, my rpi is then trying to connect as a phone - and this slot is already taken by the dexacom app on my iphone. so maybe the error is related to this? when "alternateBluetoothChannel" is true, i get no error. but the output says `scanning again in 1 minute` and this never occurs. 

> The real problem I think that needs to be resolved is in the first output log where it received a message that it didn't recognize: 0193454344ba1f424d02. The message appears to have been a copy of the message that was sent?

3. def at the limits of my bt-le knowledge. for understanding xdrip-js are there any documents anywhere that (a) explain how it works, and (b) reviews how it uses the bt-le protocol to connect to dexacom cgms? i'm trying to learn more in general - any guidance would be greatly appreciated (totally understand this project is maintained by some hard working individuals out of their own time and passion).

> I'm looking for a raspberry pi zero 2 w. As soon as I can get my hands on one, I'm going to try to get it up and running. I didn't have much success with the raspberry pi zero w boards. They would work fine for a while, then stop being able to successfully complete a full round of communication with the transmitter for a period of time, sometimes hours. After a while, it would just start working again.

4. my hero! amazing - let me know if i can be of any help with this. also, below are the steps i took to get it working on my rpi. adding here for recreating and to reduce your dev pain (and for others in the future who go down this path...). 


*installs*

```bash
## basics
sudo apt-get update; sudo apt-get upgrade
sudo apt-get install -y bluetooth bluez libbluetooth-dev libudev-dev

## node
curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
sudo apt-get install -y nodejs
## can be skipped - for using diff nodejs versions
# npm install -g n
# sudo n <node-version>

## clone repo
git clone https://github.com/xdrip-js/xdrip-js.git
cd xdrip-js

## change noble
rm package-lock.json
## remove noble from package.json
sed -i '/noble/d' package.json
## change lib/bluetooth-manager.js to use `@abandonware/noble`
sed -i "s/'noble'/'@abandonware\/noble'/g" lib/bluetooth-manager.js

# install deps
sudo npm install

# install noble (new one)
sudo npm install @abandonware/noble
```

*run it*

```bash
# run it
sudo DEBUG=smp,transmitter,bluetooth-manager node example <ID>
```

**Comment by jpcunningh** [comment]
I have xdrip-js running again on a Pi Zero 2. I don't run it by itself, though. I'm using Lookout at github.com/xdrip-js/Lookout.

I'm running the dev branch of Lookout.
